swagger: "2.0"
info: 
  description: "ArgentBank API documentation for the transaction page: contains all available API endpoints in this codebase."
  version: 1.0.0
  title: "ArgentBank : API documentation for the transactions"
  termsOfService: http://swagger.io/terms/
host: localhost:3001
basePath: /api/v2
schemes:
  - https
  - http
securityDefinitions:
  Bearer:
    type: apiKey
    in: header
    name: Authorization
paths:
  /transaction/{month}/{accountId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions for current month
      summary: An identified user can see all his transactions for the current month.
      description: "API for fetching the transactions in the current month for an identified user"
      operationId: readAllTransactions
      parameters:
      - in: header
        name: Authorization
        description: "Attach Bearer JWT token"
        type: string
        required: true
      - in: path
        name: month
        required: true
        type: string
        description: "Current month in YYYY-MM format"
      - in: path
        name: accountId
        required: true
        type: string
        description: "Account ID of the user"
      responses:
        "200":
          description: "Successfully retrieved user's all transactions for the current month"
          schema:
            type: array
            items:
              $ref: "#/definitions/TransactionDetails"
        "404":
          description: "Requested Resource Not Found"
        "500":
          description: "Internal Server Error"
  /transaction/operation/{transactionId}/{accountId}:
    get:
      security:
        - Bearer: []
      tags:
        - Read, update and delete an existent transaction
      summary: View the details of a specific transaction in another view.
      description: "API for fetching an existent transaction in detail"
      operationId: readUniqueTransaction
      parameters:
        - in: header
          name: Authorization
          description: "Attach Bearer JWT token"
          type: string
          required: true
        - in: path
          name: transactionId
          required: true
          type: integer
          description: "Transaction unique id"
        - in: path
          name: accountId
          required: true
          type: string
          description: "Account ID of the user"
      responses:
        "200":
          description: "Successfully got a user's specific transaction!"
          schema:
            $ref: "#/definitions/Transaction"
        "404":
          description: "Requested Resource Not Found"
        "500":
          description: "Internal Server Error"
    put:
      security:
        - Bearer: []
      tags:
        - Read, update and delete an existent transaction
      summary: Edit a specific transaction information for an identified user.
      description: "API for updating an existent transaction"
      operationId: updateTransaction
      parameters:
        - in: header
          name: Authorization
          description: "Attach Bearer JWT token"
          type: string
          required: true
        - in: path
          name: accountId
          required: true
          type: integer
          description: "A specific user's id"
        - in: path
          name: transactionId
          required: true
          type: integer
          description: "Transaction unique id"
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/TransactionUpdate"
      responses:
        "200":
          description: "Successfully updated a user's specific transaction!"
          schema:
            $ref: "#/definitions/Transaction"
        "404":
          description: "Requested Resource Not Found"
        "500":
          description: "Internal Server Error"
definitions:
  TransactionDetails:
    type: "object"
    properties:
      transactionId:
        type: "string"
      accountId:
        type: "string"
      date:
        type: "string"
        format: "date-time"
        example: "2023-07-07T12:34:56Z"
      description:
        type: "string"
        example: "Coffee shop purchase"
      amount:
        type: "number"
      balanceAfterTransaction:
        type: "number"
  TransactionUpdate:
    type: "object"
    properties:
      category:
        type: "string"
        description: "Category of the transaction"
      notes:
        type: "string"
        description: "Additional notes regarding the transaction"
  Transaction:
    type: "object"
    properties:
      transactionId:
        type: "string"
      accountId:
        type: "string"
      date:
        type: "string"
        format: "date-time"
      description:
        type: "string"
      amount:
        type: "number"
      balanceAfterTransaction:
        type: "number"
      category:
        type: "string"
      notes:
        type: "string"